const exercises=[
 {name:'Squat',cat:'jambes',muscles:'Quadriceps · Fessiers · Ischio-jambiers',desc:'Mouvement fondamental pour les membres inférieurs.',tips:['Pieds stables et genoux dans l’axe des orteils.','Garde le tronc gainé pendant toute la répétition.','Descends sous contrôle puis pousse fort dans le sol.']},
 {name:'Presse à cuisses',cat:'jambes',muscles:'Quadriceps · Fessiers',desc:'Travail guidé des membres inférieurs.',tips:['Bassin plaqué au dossier.','Ne verrouille pas brutalement les genoux.','Contrôle la descente.']},
 {name:'Soulevé de terre roumain',cat:'jambes',muscles:'Ischio-jambiers · Fessiers',desc:'Excellent exercice de chaîne postérieure.',tips:['Dos neutre.','Recule les hanches.','Garde la charge proche des jambes.']},
 {name:'Tirage vertical',cat:'dos',muscles:'Grand dorsal · Biceps',desc:'Développe la force de tirage verticale.',tips:['Poitrine ouverte.','Tire les coudes vers les côtes.','Évite de donner de l’élan avec le buste.']},
 {name:'Rowing',cat:'dos',muscles:'Grand dorsal · Rhomboïdes · Trapèzes',desc:'Mouvement de tirage horizontal.',tips:['Tronc stable.','Ramène les coudes vers l’arrière.','Contrôle le retour.']},
 {name:'Développé couché',cat:'pectoraux',muscles:'Pectoraux · Triceps · Deltoïdes antérieurs',desc:'Grand classique pour les pectoraux.',tips:['Omoplates fixées.','Pieds ancrés au sol.','Descente contrôlée vers le bas des pectoraux.']},
 {name:'Développé incliné',cat:'pectoraux',muscles:'Pectoraux supérieurs · Triceps',desc:'Accent sur la portion claviculaire des pectoraux.',tips:['Garde les épaules basses.','Trajectoire naturelle.','Ne cherche pas une amplitude douloureuse.']},
 {name:'Élévations latérales',cat:'epaules',muscles:'Deltoïde moyen',desc:'Isolation du faisceau moyen de l’épaule.',tips:['Légère flexion des coudes.','Monte sans élan.','Contrôle particulièrement la descente.']},
 {name:'Curl haltères',cat:'bras',muscles:'Biceps · Brachial',desc:'Exercice simple et efficace pour les biceps.',tips:['Coudes proches du corps.','Évite de balancer le buste.','Contracte en haut sans perdre le contrôle.']},
 {name:'Extension triceps poulie',cat:'bras',muscles:'Triceps',desc:'Isolation des triceps à la poulie.',tips:['Coudes fixes.','Étends complètement sans forcer les articulations.','Retour lent.']},
 {name:'Crunch à la poulie',cat:'abdos',muscles:'Grand droit de l’abdomen',desc:'Travail chargé du gainage dynamique.',tips:['Enroule la colonne plutôt que de tirer avec les bras.','Expire pendant la flexion.','Contrôle le retour.']},
 {name:'Gainage planche',cat:'abdos',muscles:'Abdominaux · Fessiers · Épaules',desc:'Renforcement global du tronc.',tips:['Corps aligné.','Contracte abdos et fessiers.','Respire normalement.']}
];
let category='all';
const grid=document.querySelector('#exercise-grid'), search=document.querySelector('#search'), count=document.querySelector('#count'), empty=document.querySelector('#empty'), modal=document.querySelector('#exercise-modal'), modalContent=document.querySelector('#modal-content');
function render(){const q=search.value.trim().toLowerCase();const list=exercises.filter(e=>(category==='all'||e.cat===category)&&(!q||`${e.name} ${e.muscles} ${e.desc}`.toLowerCase().includes(q)));grid.innerHTML=list.map((e,i)=>`<article class="card" data-index="${exercises.indexOf(e)}"><span class="tag">${e.cat}</span><h3>${e.name}</h3><p>${e.muscles}</p></article>`).join('');count.textContent=`${list.length} exercice${list.length>1?'s':''}`;empty.hidden=list.length>0;document.querySelectorAll('.card').forEach(c=>c.onclick=()=>openExercise(Number(c.dataset.index)))}
function openExercise(i){const e=exercises[i];modalContent.innerHTML=`<div class="modal"><span class="modal-tag">${e.cat}</span><h2>${e.name}</h2><p><strong>Muscles sollicités :</strong> ${e.muscles}</p><p>${e.desc}</p><h3>Points techniques</h3><ul>${e.tips.map(t=>`<li>${t}</li>`).join('')}</ul></div>`;modal.showModal()}
document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelector('.chip.active').classList.remove('active');b.classList.add('active');category=b.dataset.category;render()});search.oninput=render;document.querySelector('#close-modal').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});render();
