const exercises=[
 {id:'squat',name:'Squat',cat:'jambes',muscles:['Quadriceps','Fessiers','Ischio-jambiers'],desc:'Mouvement fondamental pour les membres inférieurs.',tips:['Pieds stables et genoux dans l’axe des orteils.','Garde le tronc gainé pendant toute la répétition.','Descends sous contrôle puis pousse fort dans le sol.'],errors:['Genoux qui rentrent vers l’intérieur.','Perte de gainage du tronc.','Charge trop lourde au détriment de la technique.'],mediaPair:['https://exercise-dataset.com/images/flat/squat-start.webp','https://exercise-dataset.com/images/flat/squat-peak.webp'],mediaSource:'https://exercise-dataset.com/exercise/squat/'},
 {id:'presse-cuisses',name:'Presse à cuisses',cat:'jambes',muscles:['Quadriceps','Fessiers'],desc:'Travail guidé des membres inférieurs.',tips:['Bassin plaqué au dossier.','Ne verrouille pas brutalement les genoux.','Contrôle la descente.'],errors:['Décoller le bassin du dossier.','Descendre sans contrôle.','Verrouiller violemment les genoux.'],mediaPair:['https://exercise-dataset.com/images/flat/leg-press-start.webp','https://exercise-dataset.com/images/flat/leg-press-peak.webp'],mediaSource:'https://exercise-dataset.com/exercise/leg-press/'},
 {id:'souleve-de-terre-roumain',name:'Soulevé de terre roumain',cat:'jambes',muscles:['Ischio-jambiers','Fessiers'],desc:'Excellent exercice de chaîne postérieure.',tips:['Dos neutre.','Recule les hanches.','Garde la charge proche des jambes.'],errors:['Arrondir le dos.','Transformer le mouvement en squat.','Éloigner la charge du corps.'],mediaPair:['https://exercise-dataset.com/images/flat/romanian-deadlift-start.webp','https://exercise-dataset.com/images/flat/romanian-deadlift-peak.webp'],mediaSource:'https://exercise-dataset.com/exercise/romanian-deadlift/'},
 {id:'tirage-vertical',name:'Tirage vertical',cat:'dos',muscles:['Grand dorsal','Biceps'],desc:'Développe la force de tirage verticale.',tips:['Poitrine ouverte.','Tire les coudes vers les côtes.','Évite de donner de l’élan avec le buste.'],errors:['Tirer principalement avec les mains.','Donner de l’élan avec le buste.','Relâcher brutalement la charge en remontée.'],mediaPair:['https://exercise-dataset.com/images/flat/lat-pulldown-start.webp','https://exercise-dataset.com/images/flat/lat-pulldown-peak.webp'],mediaSource:'https://exercise-dataset.com/exercise/lat-pulldown/'},
 {id:'rowing',name:'Rowing',cat:'dos',muscles:['Grand dorsal','Rhomboïdes','Trapèzes'],desc:'Mouvement de tirage horizontal.',tips:['Tronc stable.','Ramène les coudes vers l’arrière.','Contrôle le retour.'],errors:['Arrondir le dos.','Utiliser l’élan du corps.','Perdre la stabilité du tronc.'],mediaPair:['https://exercise-dataset.com/images/flat/barbell-row-start.webp','https://exercise-dataset.com/images/flat/barbell-row-peak.webp'],mediaSource:'https://exercise-dataset.com/exercise/barbell-row/'},
 {id:'developpe-couche',name:'Développé couché',cat:'pectoraux',muscles:['Pectoraux','Triceps','Deltoïdes antérieurs'],desc:'Grand classique pour les pectoraux.',tips:['Omoplates fixées.','Pieds ancrés au sol.','Descente contrôlée vers le bas des pectoraux.'],errors:['Décoller les épaules du banc.','Rebondir avec la barre.','Perdre le contrôle de la trajectoire.'],mediaPair:['https://exercise-dataset.com/images/flat/bench-press-start.webp','https://exercise-dataset.com/images/flat/bench-press-peak.webp'],mediaSource:'https://exercise-dataset.com/exercise/bench-press/'},
 {id:'developpe-incline',name:'Développé incliné',cat:'pectoraux',muscles:['Pectoraux supérieurs','Triceps'],desc:'Accent sur la portion claviculaire des pectoraux.',tips:['Garde les épaules basses.','Trajectoire naturelle.','Ne cherche pas une amplitude douloureuse.'],errors:['Épaules qui remontent vers les oreilles.','Descente incontrôlée.','Amplitude forcée au détriment du confort.'],mediaPair:['https://exercise-dataset.com/images/flat/incline-bench-press-start.webp','https://exercise-dataset.com/images/flat/incline-bench-press-peak.webp'],mediaSource:'https://exercise-dataset.com/exercise/incline-bench-press/'},
 {id:'elevations-laterales',name:'Élévations latérales',cat:'epaules',muscles:['Deltoïde moyen'],desc:'Isolation du faisceau moyen de l’épaule.',tips:['Légère flexion des coudes.','Monte sans élan.','Contrôle particulièrement la descente.'],errors:['Prendre trop lourd.','Balancer le buste.','Transformer le mouvement en tirage.'],mediaPair:['https://exercise-dataset.com/images/flat/lateral-raise-start.webp','https://exercise-dataset.com/images/flat/lateral-raise-peak.webp'],mediaSource:'https://exercise-dataset.com/exercise/lateral-raise/'},
 {id:'curl-halteres',name:'Curl haltères',cat:'bras',muscles:['Biceps','Brachial'],desc:'Exercice simple et efficace pour les biceps.',tips:['Coudes proches du corps.','Évite de balancer le buste.','Contracte en haut sans perdre le contrôle.'],errors:['Balancer le corps.','Avancer les coudes excessivement.','Utiliser une charge qui empêche le contrôle.'],mediaPair:['https://exercise-dataset.com/images/flat/bicep-curl-start.webp','https://exercise-dataset.com/images/flat/bicep-curl-peak.webp'],mediaSource:'https://exercise-dataset.com/exercise/bicep-curl/'},
 {id:'extension-triceps-poulie',name:'Extension triceps poulie',cat:'bras',muscles:['Triceps'],desc:'Isolation des triceps à la poulie.',tips:['Coudes fixes.','Étends complètement sans forcer les articulations.','Retour lent.'],errors:['Écarter les coudes.','Utiliser l’élan du corps.','Laisser remonter la charge brutalement.'],mediaPair:['https://exercise-dataset.com/images/flat/tricep-pushdown-start.webp','https://exercise-dataset.com/images/flat/tricep-pushdown-peak.webp'],mediaSource:'https://exercise-dataset.com/exercise/tricep-pushdown/'},
 {id:'crunch-poulie',name:'Crunch à la poulie',cat:'abdos',muscles:['Grand droit de l’abdomen'],desc:'Travail chargé du gainage dynamique.',tips:['Enroule la colonne plutôt que de tirer avec les bras.','Expire pendant la flexion.','Contrôle le retour.'],errors:['Tirer uniquement avec les bras.','Utiliser trop d’élan.','Perdre le contrôle de la remontée.'],mediaPair:['https://exercise-dataset.com/images/flat/cable-crunch-start.webp','https://exercise-dataset.com/images/flat/cable-crunch-peak.webp'],mediaSource:'https://exercise-dataset.com/exercise/cable-crunch/'},
 {id:'gainage-planche',name:'Gainage planche',cat:'abdos',muscles:['Abdominaux','Fessiers','Épaules'],desc:'Renforcement global du tronc.',tips:['Corps aligné.','Contracte abdos et fessiers.','Respire normalement.'],errors:['Creuser le bas du dos.','Lever excessivement les fesses.','Bloquer la respiration.'],mediaPair:['https://exercise-dataset.com/images/flat/plank-main.webp','https://exercise-dataset.com/images/flat/plank-main.webp'],mediaSource:'https://exercise-dataset.com/exercise/plank/'},
 {id:'crunch-leste',name:'Crunch lesté derrière la tête',cat:'abdos',muscles:['Grand droit de l’abdomen','Obliques'],desc:'Exercice abdominal animé avec une charge tenue derrière la tête.',tips:['Enroule le haut du corps de façon contrôlée.','Garde le mouvement centré sur les abdominaux.','Contrôle la phase de retour.'],errors:['Tirer sur la nuque.','Donner de l’élan.','Descendre trop rapidement.'],media:'https://gymvisual.com/img/p/5/9/3/5/5935.gif',mediaCredit:'Animation gratuite : Gym visual — Aliaksandr Makatserchyk',mediaSource:'https://gymvisual.com/free/2694-weighted-crunch-behind-head.html'}
];
let category='all';
const grid=document.querySelector('#exercise-grid'), search=document.querySelector('#search'), count=document.querySelector('#count'), empty=document.querySelector('#empty'), modal=document.querySelector('#exercise-modal'), modalContent=document.querySelector('#modal-content');
const categoryNames={jambes:'Jambes',dos:'Dos',pectoraux:'Pectoraux',epaules:'Épaules',bras:'Bras',abdos:'Abdos'};
function mediaHtml(e,modalView=false){if(e.media)return `<div class="media-frame"><img src="${e.media}" alt="Animation ${e.name}" loading="lazy"></div>`;if(e.mediaPair)return `<div class="media-frame media-pair"><img class="media-a" src="${e.mediaPair[0]}" alt="Illustration ${e.name} position 1" loading="lazy"><img class="media-b" src="${e.mediaPair[1]}" alt="Illustration ${e.name} position 2" loading="lazy"></div>`;return ''}
function render(){const q=search.value.trim().toLowerCase();const list=exercises.filter(e=>(category==='all'||e.cat===category)&&(!q||`${e.name} ${e.muscles.join(' ')} ${e.desc}`.toLowerCase().includes(q)));grid.innerHTML=list.map(e=>`<article class="card ${e.media||e.mediaPair?'card-media':''}" data-id="${e.id}">${mediaHtml(e)}<span class="tag">${categoryNames[e.cat]}</span><h3>${e.name}</h3><p>${e.muscles.join(' · ')}</p></article>`).join('');count.textContent=`${list.length} exercice${list.length>1?'s':''}`;empty.hidden=list.length>0;document.querySelectorAll('.card').forEach(c=>c.onclick=()=>openExercise(c.dataset.id))}
function exerciseUrl(e){const url=new URL(window.location.href);url.search='';url.hash='';url.searchParams.set('exercice',e.id);return url.toString()}
function openExercise(id,updateUrl=true){const e=exercises.find(x=>x.id===id);if(!e)return;if(updateUrl)history.pushState({exercice:e.id},'',exerciseUrl(e));modalContent.innerHTML=`<div class="modal"><span class="modal-tag">${categoryNames[e.cat]}</span><h2>${e.name}</h2>${mediaHtml(e,true)}<div class="modal-muscles">${e.muscles.map(m=>`<span class="modal-muscle">${m}</span>`).join('')}</div><p>${e.desc}</p><h3>Points techniques</h3><ul>${e.tips.map(t=>`<li>${t}</li>`).join('')}</ul><div class="modal-errors"><h3>Erreurs à éviter</h3><ul>${e.errors.map(t=>`<li>${t}</li>`).join('')}</ul></div>${e.mediaSource?`<a class="media-source" href="${e.mediaSource}" target="_blank" rel="noopener">Source du visuel ↗</a>`:'<div class="modal-video">🎥 Zone vidéo — ajoute ta démonstration pour cet exercice</div>'}<div class="qr-section"><h3>QR code de cet exercice</h3><p>Scanne ce QR code pour ouvrir directement cette fiche.</p><div id="qrcode" class="qr-code"></div><div class="qr-url"><input id="exercise-link" value="${exerciseUrl(e)}" readonly><button class="qr-copy" id="copy-link">Copier le lien</button></div></div></div>`;modal.showModal();generateQR(e)}
function generateQR(e){const box=document.querySelector('#qrcode');if(!box||typeof QRCode==='undefined')return;box.innerHTML='';new QRCode(box,{text:exerciseUrl(e),width:220,height:220,colorDark:'#000000',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.H});const button=document.querySelector('#copy-link');button.onclick=async()=>{try{await navigator.clipboard.writeText(exerciseUrl(e));button.textContent='Lien copié ✓';setTimeout(()=>button.textContent='Copier le lien',1800)}catch{button.textContent='Copie impossible'}}}
function openFromUrl(){const id=new URLSearchParams(window.location.search).get('exercice');if(id)openExercise(id,false)}
document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelector('.chip.active').classList.remove('active');b.classList.add('active');category=b.dataset.category;render()});search.oninput=render;document.querySelector('#close-modal').onclick=()=>{modal.close();history.pushState({},'',window.location.pathname)};modal.addEventListener('click',e=>{if(e.target===modal){modal.close();history.pushState({},'',window.location.pathname)}});window.addEventListener('popstate',()=>{if(!new URLSearchParams(window.location.search).get('exercice')&&modal.open)modal.close()});render();openFromUrl();
