// Traductions françaises prioritaires — HS Coaching
// Les exercices non présents ici utilisent progressivement les données françaises disponibles.
const HS_FR={
  'barbell bench press':{name:'Développé couché à la barre',description:'Exercice de base pour développer les pectoraux, avec une forte participation des triceps et des épaules.',instructions:['Allonge-toi sur le banc, les pieds fermement au sol et les omoplates rapprochées.','Saisis la barre légèrement plus large que les épaules et décroche-la en gardant les poignets stables.','Descends la barre de façon contrôlée vers le bas des pectoraux, sans perdre le placement des épaules.','Pousse la barre vers le haut jusqu’à presque tendre les bras, sans relâcher le contrôle.'],tips:['Garde les omoplates fixées au banc.','Évite de rebondir avec la barre sur la poitrine.','Choisis une charge qui te permet de conserver une trajectoire régulière.']},
  'barbell deadlift':{name:'Soulevé de terre à la barre',description:'Mouvement global sollicitant principalement la chaîne postérieure : fessiers, ischio-jambiers et muscles du dos.',instructions:['Place les pieds sous la barre et rapproche-la au maximum de tes tibias.','Fléchis les hanches et les genoux pour saisir la barre en gardant le dos neutre.','Pousse dans le sol et accompagne la barre près des jambes jusqu’à la position debout.','Redescends la barre en contrôlant d’abord les hanches puis les genoux.'],tips:['Garde la barre proche du corps pendant tout le mouvement.','Ne cherche pas à arrondir le dos pour gagner de l’amplitude.','Verrouille la position finale sans exagérer l’extension lombaire.']},
  'barbell full squat':{name:'Squat complet à la barre',description:'Mouvement fondamental pour développer les quadriceps, les fessiers et l’ensemble de la chaîne inférieure.',instructions:['Place la barre confortablement sur le haut du dos et adopte une position stable.','Inspire, gaine le tronc et descends en pliant simultanément les hanches et les genoux.','Descends à l’amplitude que ta mobilité permet tout en conservant un bon contrôle.','Pousse dans le sol pour revenir debout en gardant les genoux dans l’axe des pieds.'],tips:['Garde les pieds fermement ancrés au sol.','Évite que les genoux rentrent vers l’intérieur.','La profondeur doit rester compatible avec une technique propre.']},
  'dumbbell biceps curl':{name:'Curl biceps avec haltères',description:'Exercice d’isolation destiné principalement au développement des biceps.',instructions:['Tiens un haltère dans chaque main, bras le long du corps.','Garde les coudes proches du buste et fléchis les bras pour monter les haltères.','Contracte les biceps en haut du mouvement sans avancer les coudes.','Redescends lentement jusqu’à presque tendre complètement les bras.'],tips:['Évite de donner de l’élan avec le dos.','Contrôle particulièrement la phase de descente.','Garde les épaules basses et détendues.']},
  'pull-up':{name:'Tractions',description:'Exercice au poids du corps sollicitant principalement le grand dorsal, avec une forte participation des biceps.',instructions:['Saisis la barre et démarre bras tendus, épaules contrôlées.','Gaine le tronc et tire les coudes vers le bas et vers l’arrière.','Monte jusqu’à amener le menton au niveau de la barre ou selon ton amplitude maîtrisée.','Redescends sous contrôle jusqu’à la position de départ.'],tips:['Évite de balancer le corps.','Pense à tirer avec les coudes plutôt qu’avec les mains.','Adapte l’assistance ou la charge pour conserver une amplitude propre.']},
  'dumbbell lateral raise':{name:'Élévations latérales avec haltères',description:'Exercice d’isolation ciblant principalement le deltoïde moyen.',instructions:['Tiens les haltères le long du corps avec une légère flexion des coudes.','Élève les bras sur les côtés en contrôlant le mouvement.','Monte jusqu’à environ la hauteur des épaules selon ta mobilité.','Redescends lentement sans relâcher la tension.'],tips:['Évite de hausser les épaules.','Utilise une charge permettant un mouvement strict.','Ne transforme pas l’exercice en mouvement d’élan.']}
};
