from pathlib import Path
import re
p=Path('programmes.html'); s=p.read_text()
css='.workout-summary-history{width:100%;margin-top:9px;border:1px solid #333;border-radius:11px;background:#191919;color:#fff;padding:13px;font-size:12px;font-weight:900;cursor:pointer}.history-overlay{position:fixed;inset:0;z-index:6000;background:rgba(0,0,0,.96);display:grid;place-items:center;padding:14px}.history-overlay[hidden]{display:none}.history-panel{width:min(620px,100%);max-height:92vh;overflow:auto;background:#151515;border:1px solid #333;border-radius:22px;padding:22px 18px}.history-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;margin-bottom:18px}.history-kicker{font-size:9px;letter-spacing:1.5px;color:#777;font-weight:900}.history-head h2{margin:6px 0 0;font-size:26px}.history-close{width:38px;height:38px;border-radius:50%;border:1px solid #333;background:#222;color:#fff;font-size:22px}.history-card{background:#101010;border:1px solid #292929;border-radius:14px;padding:14px;margin-bottom:9px}.history-date{font-size:9px;color:#777}.history-program{font-size:14px;font-weight:900;margin-top:5px}.history-meta{font-size:10px;color:#999;margin-top:5px}.history-exercise{display:flex;justify-content:space-between;gap:12px;padding:9px 0;border-top:1px solid #222;margin-top:10px;font-size:10px}.history-exercise strong{font-size:11px}.history-empty{color:#777;font-size:11px;line-height:1.6;text-align:center;padding:24px 8px}.history-section-title{font-size:9px;letter-spacing:1.3px;color:#777;font-weight:900;margin:18px 0 8px;text-transform:uppercase}.history-best{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;background:#101010;border:1px solid #292929;border-radius:12px;padding:11px}.history-best strong{font-size:11px}.history-best span{font-size:11px;font-weight:900}.history-note{font-size:9px;color:#666;line-height:1.5;margin-top:14px}@media(max-width:650px){.history-panel{border-radius:18px;padding:19px 14px}.history-head h2{font-size:23px}}'
marker='.workout-summary-close{width:100%;border:0;border-radius:11px;background:#fff;color:#000;padding:14px;font-size:12px;font-weight:900;cursor:pointer}'
if css not in s:s=s.replace(marker,marker+css,1)
state=re.search(r'let programs=.*?;',s)
if not state: raise SystemExit('state missing')
if 'const HISTORY_KEY=' not in s:
 insert="""
const HISTORY_KEY='hs_workout_history_v1';
function readWorkoutHistory(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch(e){return[]}}
function latestExercisePerformance(id){const h=readWorkoutHistory();for(const session of h){const ex=(session.exercises||[]).find(x=>String(x.exercise_id)===String(id));if(ex)return ex}return null}
function saveWorkoutHistory(){const st=workoutState;if(!st)return;const session=st.session,values=st.values||{};const exercises=session.items.map((r,i)=>{const rows=values[i]||[];return{exercise_id:r.exercise_id,name:session.names[r.exercise_id]||'Exercice',sets:rows.filter(v=>v.done||v.load!==''||v.reps!=='').map((v,n)=>({set:n+1,load:v.load||'',reps:v.reps||''}))}});const item={date:new Date().toISOString(),program_name:activeProgram?.name||'Programme',session_name:session.name||'Séance',duration_minutes:Math.max(1,Math.round((Date.now()-(st.startedAt||Date.now()))/60000)),exercises};const h=readWorkoutHistory();h.unshift(item);localStorage.setItem(HISTORY_KEY,JSON.stringify(h.slice(0,50)))}
function openHistory(){renderHistory();document.getElementById('historyOverlay').hidden=false;document.body.style.overflow='hidden'}
function closeHistory(){document.getElementById('historyOverlay').hidden=true;document.body.style.overflow=workoutState||!document.getElementById('programOverlay').hidden?'hidden':''}
function renderHistory(){const h=readWorkoutHistory(),el=document.getElementById('historyContent');if(!h.length){el.innerHTML='<div class="history-empty">Aucune séance enregistrée pour le moment.<br>Termine une séance pour commencer à suivre ta progression.</div>';return}el.innerHTML='<div class="history-section-title">Dernières séances</div>'+h.slice(0,8).map(s=>'<article class="history-card"><div class="history-date">'+new Date(s.date).toLocaleDateString('fr-FR',{day:'2-digit',month:'short',year:'numeric'})+' · '+s.duration_minutes+' min</div><div class="history-program">'+esc(s.program_name)+'</div><div class="history-meta">'+esc(s.session_name)+' · '+s.exercises.length+' exercices</div>'+s.exercises.filter(e=>e.sets.length).slice(0,5).map(e=>'<div class="history-exercise"><strong>'+esc(e.name)+'</strong><span>'+e.sets.map(x=>esc((x.load||'—')+' kg × '+(x.reps||'—'))).join(' · ')+'</span></div>').join('')+'</article>').join('')+'<div class="history-section-title">À retenir</div><div class="history-best"><strong>'+h.length+' séance'+(h.length>1?'s':'')+' enregistrée'+(h.length>1?'s':'')+'</strong><span>Progression en cours</span></div><div class="history-note">Historique enregistré sur cet appareil. La prochaine étape permettra de le retrouver sur plusieurs appareils avec un compte client.</div>'}
"""
 s=s[:state.end()]+insert+s[state.end():]
old="st.values[key]??=Array.from({length:sets},()=>({load:r.load||'',reps:'',done:false}));";new="st.values[key]??=(()=>{const previous=latestExercisePerformance(id),seed=previous?.sets?.[0]||{};return Array.from({length:sets},()=>({load:seed.load||r.load||'',reps:seed.reps||'',done:false}))})();";s=s.replace(old,new,1)
s=s.replace("function finishWorkout(){clearInterval(restTimer);document.getElementById('workoutOverlay').hidden=true;document.body.style.overflow='hidden';showWorkoutSummary()}","function finishWorkout(){clearInterval(restTimer);saveWorkoutHistory();document.getElementById('workoutOverlay').hidden=true;document.body.style.overflow='hidden';showWorkoutSummary()}",1)
s=s.replace('<button class="workout-summary-close" onclick="closeWorkoutSummary()">Retour au programme</button>','<button class="workout-summary-history" onclick="openHistory()">Voir ma progression</button><button class="workout-summary-close" onclick="closeWorkoutSummary()">Retour au programme</button>',1)
overlay='<div id="historyOverlay" class="history-overlay" hidden onclick="if(event.target===this)closeHistory()"><section class="history-panel"><div class="history-head"><div><div class="history-kicker">SUIVI PERSONNEL</div><h2>Ma progression</h2></div><button class="history-close" onclick="closeHistory()">×</button></div><div id="historyContent"></div></section></div>'
if 'id="historyOverlay"' not in s:s=s.replace('</body></html>',overlay+'</body></html>',1)
p.write_text(s)
